import { ABILITY_OPTIONS, ABILITY_WITH_AUTO_OPTIONS, CONDITION_OPTIONS, CREATURE_TYPE_OPTIONS, DAMAGE_TYPE_OPTIONS, RESTORE_OPTIONS, SIZE_OPTIONS } from './gameCoreShared.js';
import { enumArrayField, formulaField, namedDetailsRows, nestedField, objectField, options, referenceArrayField, referenceField, repeatableField, section, source, stringArrayField, variableField } from './gameCoreHelpers.js';
const p=(t,...x)=>source(t,...x), o=options;
const progressionRows=(key,type)=>{const label=type==='Класс'?'Прогрессия':'Прогрессия по уровням'; const sp=child=>type==='Класс'?p(type,label,child):null; return repeatableField(key,label,[
  nestedField(`${key}.level`,'Уровень','integer',{},sp('Уровень')),
  nestedField(`${key}.proficiencyBonus`,'Бонус мастерства','integer',{},sp('Бонус мастерства')),
  referenceArrayField(`${key}.skills`,'Навыки/особенности',['skill'],{},sp('Навыки/особенности'),true),
  referenceArrayField(`${key}.resources`,'Ресурсы',['item','lore'],{},sp('Ресурсы'),true),
  referenceArrayField(`${key}.spells`,'Заклинания',['spell'],{},sp('Заклинания'),true),
  namedDetailsRows(`${key}.choices`,'Выборы',sp('Выборы'),true),
  nestedField(`${key}.abilityScoreImprovement`,'Улучшение характеристик/черты','boolean',{},sp('Улучшение характеристик/черты')),
  namedDetailsRows(`${key}.scalingValues`,'Значения масштабирования',sp('Значения масштабирования'),true)
],{section:'progression'},p(type,label));};

const raceFields=[
  referenceArrayField('race.variants','Подраса/вариант',['race'],{section:'identity'},p('Раса','Подраса/вариант')),
  referenceField('race.parent','Родительская раса',['race'],{section:'identity'},p('Раса','Родительская раса')),
  variableField('race.creatureType','Тип существа','enum',{options:CREATURE_TYPE_OPTIONS,section:'identity'},p('Раса','Тип существа')),
  objectField('race.size','Размер',[nestedField('race.size.value','Значение','enum',{options:SIZE_OPTIONS},p('Раса','Размер','Значение')),enumArrayField('race.size.choices','Выбор',SIZE_OPTIONS,{},p('Раса','Размер','Выбор'),true)],{section:'identity'},p('Раса','Размер')),
  objectField('race.age','Возраст',[nestedField('race.age.adulthood','Взросление','integer',{},p('Раса','Возраст','Взросление')),nestedField('race.age.average','Средняя продолжительность жизни','integer',{},p('Раса','Возраст','Средняя продолжительность жизни')),nestedField('race.age.maximum','Максимальный возраст','integer',{},p('Раса','Возраст','Максимальный возраст'))],{section:'identity'},p('Раса','Возраст')),
  objectField('race.movement','Передвижение',['Ходьба','Полёт','Плавание','Лазание','Рытьё'].map((l,i)=>nestedField(`race.movement.${['walk','fly','swim','climb','burrow'][i]}`,l,'number',{},p('Раса','Передвижение',l))),{section:'traits'},p('Раса','Передвижение')),
  repeatableField('race.abilities','Характеристики',[nestedField('race.abilities.ability','Характеристика','enum',{options:ABILITY_WITH_AUTO_OPTIONS},p('Раса','Характеристики','Характеристика')),nestedField('race.abilities.bonus','Бонус','number',{},p('Раса','Характеристики','Бонус')),nestedField('race.abilities.choice','Выбор','boolean',{},p('Раса','Характеристики','Выбор')),nestedField('race.abilities.maximum','Максимум','integer',{},p('Раса','Характеристики','Максимум'))],{section:'traits'},p('Раса','Характеристики')),
  objectField('race.languages','Языки',[stringArrayField('race.languages.fixed','Фиксированные',{},p('Раса','Языки','Фиксированные'),true),stringArrayField('race.languages.choices','Выбираемые',{},p('Раса','Языки','Выбираемые'),true),nestedField('race.languages.choiceCount','Количество выбора','integer',{},p('Раса','Языки','Количество выбора'))],{section:'traits'},p('Раса','Языки')),
  objectField('race.senses','Чувства',[nestedField('race.senses.darkvision','Тёмное зрение','number',{},p('Раса','Чувства','Тёмное зрение')),nestedField('race.senses.blindsight','Слепое зрение','number',{},p('Раса','Чувства','Слепое зрение')),nestedField('race.senses.truesight','Истинное зрение','number',{},p('Раса','Чувства','Истинное зрение')),namedDetailsRows('race.senses.other','Другие',p('Раса','Чувства','Другие'),true)],{section:'traits'},p('Раса','Чувства')),
  objectField('race.proficiencies','Владения',[stringArrayField('race.proficiencies.weapons','Оружие',{},p('Раса','Владения','Оружие'),true),stringArrayField('race.proficiencies.armor','Доспехи',{},p('Раса','Владения','Доспехи'),true),stringArrayField('race.proficiencies.tools','Инструменты',{},p('Раса','Владения','Инструменты'),true),namedDetailsRows('race.proficiencies.skills','Навыки',p('Раса','Владения','Навыки'),true)],{section:'traits'},p('Раса','Владения')),
  enumArrayField('race.resistances','Сопротивления',DAMAGE_TYPE_OPTIONS,{section:'defense'},p('Раса','Сопротивления')),
  enumArrayField('race.immunities','Иммунитеты',DAMAGE_TYPE_OPTIONS,{section:'defense'},p('Раса','Иммунитеты')),
  enumArrayField('race.conditionImmunities','Иммунитеты к состояниям',CONDITION_OPTIONS,{section:'defense'},p('Раса','Иммунитеты к состояниям')),
  referenceArrayField('race.skills','Навыки/особенности',['skill'],{section:'grants'},p('Раса','Навыки/особенности')),
  referenceArrayField('race.spells','Заклинания',['spell'],{section:'grants'},p('Раса','Заклинания')),
  referenceArrayField('race.effects','Эффекты',['effect'],{section:'grants'},p('Раса','Эффекты')),
  referenceArrayField('race.items','Предметы',['item'],{section:'grants'},p('Раса','Предметы')),
  referenceArrayField('race.acquisitionChoices','Выборы при получении расы',['skill','item','spell','effect'],{section:'progression'},p('Раса','Выборы при получении расы')),
  progressionRows('race.progression','Раса'),stringArrayField('race.requirements','Требования',{section:'requirements'},p('Раса','Требования'))
];

const classFields=[
  referenceArrayField('class.subclasses','Подклассы',['class'],{section:'identity'},p('Класс','Подклассы')),
  enumArrayField('class.primaryAbilities','Основная характеристика',ABILITY_OPTIONS,{section:'identity'},p('Класс','Основная характеристика')),
  enumArrayField('class.secondaryAbilities','Дополнительные характеристики',ABILITY_OPTIONS,{section:'identity'},p('Класс','Дополнительные характеристики')),
  variableField('class.hitDie','Кость хитов','enum',{options:o(['d6','d8','d10','d12','custom']),section:'identity'},p('Класс','Кость хитов')),
  objectField('class.hitPoints','Хиты',[formulaField('class.hitPoints.firstLevel','На первом уровне',{},p('Класс','Хиты','На первом уровне'),true),formulaField('class.hitPoints.nextLevels','На следующих уровнях',{},p('Класс','Хиты','На следующих уровнях'),true),formulaField('class.hitPoints.formula','Формула',{},p('Класс','Хиты','Формула'),true)],{section:'identity'},p('Класс','Хиты')),
  objectField('class.proficiencies','Владения',[stringArrayField('class.proficiencies.armor','Доспехи',{},p('Класс','Владения','Доспехи'),true),stringArrayField('class.proficiencies.weapons','Оружие',{},p('Класс','Владения','Оружие'),true),stringArrayField('class.proficiencies.tools','Инструменты',{},p('Класс','Владения','Инструменты'),true),enumArrayField('class.proficiencies.savingThrows','Спасброски',ABILITY_OPTIONS,{},p('Класс','Владения','Спасброски'),true),objectField('class.proficiencies.skills','Навыки',[enumArrayField('class.proficiencies.skills.available','Доступные',o(['acrobatics','arcana','athletics','perception','survival','performance','intimidation','history','sleight-of-hand','medicine','deception','nature','insight','religion','stealth','persuasion','animal-handling','investigation']),{},p('Класс','Владения','Навыки','Доступные'),true),nestedField('class.proficiencies.skills.choiceCount','Количество выбора','integer',{},p('Класс','Владения','Навыки','Количество выбора'))],{},p('Класс','Владения','Навыки'),true)],{section:'proficiencies'},p('Класс','Владения')),
  referenceArrayField('class.startingEquipment','Начальное снаряжение',['item'],{section:'proficiencies'},p('Класс','Начальное снаряжение')),
  repeatableField('class.startingMoney','Начальные деньги',[nestedField('class.startingMoney.currency','Валюта'),nestedField('class.startingMoney.amount','Сумма','number'),formulaField('class.startingMoney.formula','Формула',{},null,true)],{section:'proficiencies'},p('Класс','Начальные деньги')),
  objectField('class.multiclass','Мультикласс',[stringArrayField('class.multiclass.requirements','Требования',{},p('Класс','Мультикласс','Требования'),true),namedDetailsRows('class.multiclass.proficiencies','Получаемые владения',p('Класс','Мультикласс','Получаемые владения'),true)],{section:'requirements'},p('Класс','Мультикласс')),
  objectField('class.spellcasting','Заклинания',[nestedField('class.spellcasting.enabled','Использует магию','boolean',{},p('Класс','Заклинания','Использует магию')),nestedField('class.spellcasting.ability','Характеристика','enum',{options:ABILITY_WITH_AUTO_OPTIONS},p('Класс','Заклинания','Характеристика')),nestedField('class.spellcasting.progression','Тип прогрессии','enum',{options:o(['full','half','third','pact','custom'])},p('Класс','Заклинания','Тип прогрессии')),nestedField('class.spellcasting.preparation','Подготовка','enum',{options:o(['known','prepared','spellbook','always-prepared','custom'])},p('Класс','Заклинания','Подготовка')),namedDetailsRows('class.spellcasting.knownByLevel','Известные заклинания по уровням',p('Класс','Заклинания','Известные заклинания по уровням'),true),namedDetailsRows('class.spellcasting.cantripsByLevel','Заговоры по уровням',p('Класс','Заклинания','Заговоры по уровням'),true),namedDetailsRows('class.spellcasting.slotsByLevel','Ячейки по уровням',p('Класс','Заклинания','Ячейки по уровням'),true),nestedField('class.spellcasting.rituals','Ритуалы','boolean',{},p('Класс','Заклинания','Ритуалы')),referenceField('class.spellcasting.focus','Фокус',['item'],{},p('Класс','Заклинания','Фокус'),true)],{section:'spellcasting'},p('Класс','Заклинания')),
  progressionRows('class.progression','Класс'),
  repeatableField('class.resources','Ресурсы',[nestedField('class.resources.name','Название','string',{},p('Класс','Ресурсы','Название')),nestedField('class.resources.maximum','Максимум','integer',{},p('Класс','Ресурсы','Максимум')),formulaField('class.resources.maximumFormula','Формула максимума',{},p('Класс','Ресурсы','Формула максимума'),true),nestedField('class.resources.recovery','Восстановление','enum',{options:RESTORE_OPTIONS},p('Класс','Ресурсы','Восстановление'))],{section:'progression'},p('Класс','Ресурсы')),
  referenceArrayField('class.skills','Навыки/особенности',['skill'],{section:'grants'},p('Класс','Навыки/особенности')),referenceArrayField('class.effects','Предоставляемые эффекты',['effect'],{section:'grants'},p('Класс','Предоставляемые эффекты')),stringArrayField('class.grantedProficiencies','Предоставляемые владения',{section:'grants'},p('Класс','Предоставляемые владения')),referenceArrayField('class.items','Предоставляемые предметы',['item'],{section:'grants'},p('Класс','Предоставляемые предметы')),
  objectField('class.subclass','Подкласс',[nestedField('class.subclass.selectionLevel','Уровень выбора','integer',{},p('Класс','Подкласс','Уровень выбора')),referenceArrayField('class.subclass.available','Доступные подклассы',['class'],{},p('Класс','Подкласс','Доступные подклассы'),true)],{section:'progression'},p('Класс','Подкласс')),
  stringArrayField('class.requirements','Требования',{section:'requirements'},p('Класс','Требования'))
];
const sections=[section('card','Карточка',0),section('identity','Основное',10),section('traits','Свойства',20),section('defense','Защиты',30),section('proficiencies','Владения',30),section('spellcasting','Заклинания',40),section('grants','Предоставляемое',50),section('progression','Прогрессия',60),section('requirements','Требования',70),section('publication','Публикация',80)];
export const RACE_DEFINITION={id:'race',version:1,label:'Раса',includes:[{id:'core.card-metadata',version:1},{id:'dnd.rule-publication',version:1}],fields:raceFields,sections,capabilities:{gameplayRule:true,characterOption:true},metadata:{stage:5,catalog:'game-core'}};
export const CLASS_DEFINITION={id:'class',version:1,label:'Класс',includes:[{id:'core.card-metadata',version:1},{id:'dnd.rule-publication',version:1}],fields:classFields,sections,capabilities:{gameplayRule:true,characterOption:true},metadata:{stage:5,catalog:'game-core'}};
