import { deepFreeze } from '../definitionIdentity.js';
import {
  LOCATION_DEFINITION, REGION_DEFINITION, COUNTRY_DEFINITION, ORGANIZATION_DEFINITION
} from './worldGeographyDefinitions.js';
import { LORE_DEFINITION, FOLDER_DEFINITION, PROJECT_DEFINITION } from './worldServiceDefinitions.js';

export const WORLD_SERVICE_CARD_TYPE_DEFINITIONS = deepFreeze([
  LOCATION_DEFINITION, REGION_DEFINITION, COUNTRY_DEFINITION, ORGANIZATION_DEFINITION,
  LORE_DEFINITION, FOLDER_DEFINITION, PROJECT_DEFINITION
]);

export const WORLD_SERVICE_FIELD_SET_DEFINITIONS = deepFreeze([]);
